baseurl: "https://logmeetupmadrid.github.io/"
title: "LoG Madrid"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "LoG Madrid"
  Description: "LoG Meet Up Madrid"
  Date: "November 27 - 29 th"
  #Price: "Only XX€" # If your event is free, just comment this line
  Venue: "Madrid"
  Address: "Edificio XXX, Calle XXX, NN"
  City:  "Spain"
  State: "Madrid"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - registration
    - cfp
    - schedule
    - speakers
    - sponsors
    #- partners
    - organizers 
    - location

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    registration: "Registration"
    cfp: "Call for talks"
    location: "The Venue"
    schedule: "Schedule"
    speakers: "Speakers"
    sponsors: "Sponsors"
    partners: "Partners"
    organizers: "Organizers"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Call for Talks"
  #  link: "#cfp" ## CHANGE THIS !!!

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:

    - name: "Grupo Antonio G. Marques"
      logo: "/img/logo_urjc-2.jpg"
      url: "https://www.tsc.urjc.es/~amarques/"

    - name: "CIMA BioComp"
      logo: "/img/LogoCima.png"
      url: "https://cima.cun.es/investigacion/programas-investigacion/programa-investigacion-biologia-computacional"

  # List of Partners
  # Partners:
  #   - name: "Michi"
  #     logo: "/img/paw.png"
  #     #url: "https://gohugo.io"
  #   - name: "Michi"
  #     logo: "/img/paw.png"
  #     #url: "http://braziljs.org"

  # The entire schedule
  Schedule:

    - name: "Check-in & Opening"
      time: "Monday"

    - name: "Plenary Talk Title: TBA" # Name Surname
      photo: "/img/reinhard_1_.jpg"
      bio: "Professor for Machine Learning at the Department of Computer Engineering at TUM (Technical University of Munich)."
      company: "Technical University of Munich" # Cat Foundation
      link:
        href: "https://www.professoren.tum.de/en/heckel-reinhard"
      #  text: "WebPage"
      presentation:
        title: "Reinhard Heckel" #Speaker Name
        time: "Monday"

    - name: "Long Talks"
      time: "Monday"

    - name: "Pitch Talks + Poster"
      time: "Monday"

    - name: "Join LoG Conference"
      time: "Monday"


    - name: "Plenary Talk Title: TBA" # Name Surname
      photo: "/img/ivan2.jpeg"
      bio: "Associate Professor at the Department of Mathematics and Computer Science of the University of Basel."      #company: "TBA" # Cat Foundation
      company: "University of Basel"
      link: 
        href: "https://dmi.unibas.ch/de/personen/ivan-dokmanic/"
      #  text: "@linus"
      presentation:
        title: "Ivan Dokmanić " # Speaker Name
        time: "Tuesday"


    - name: "Long Talks"
      time: "Tuesday"

    - name: "Pitch Talks + Poster"
      time: "Tuesday"

    - name: "Join LoG Conference"
      time: "Tuesday"


    - name: "Plenary Talk Title: TBA" # Name Surname
      photo: "/img/xiaowen.jpg"
      url: "www.example.org"
      bio: " Associate professor in the Department of Engineering Science at the University of Oxford."
      company: "University of Oxford" # Cat Foundation
      link:
        href: "https://eng.ox.ac.uk/people/xiaowen-dong/"
        #text: "@linus"
      presentation:
        title: "Xiaowen Dong" # Speaker Name
        time: "Wednesday"

    - name: "Long Talks"
      time: "Wednesday"

    - name: "Pitch Talks + Poster"
      time: "Wednesday"

    - name: "Join LoG Conference"
      time: "Wednesday"


  # List of Contacts
  Contacts:

    - name: "Antonio G. Marqués"
      logo: "/img/antoniogmarques.jpg"
      email: "antonio.garcia.marques@urjc.es"
      affiliation: "Universidad Rey Juan Carlos"
      #url: "https://gohugo.io"
      home: "https://tsc.urjc.es/~amarques/" 
      linkedin: "https://es.linkedin.com/in/antonio-garc%C3%ADa-marqu%C3%A9s-1ba65254" 
      googleScholar: "https://scholar.google.com/citations?user=d05JMMkAAAAJ&hl=en" 

    - name: "Mikel Hernaez"
      logo: "/img/mikelhernaez.jpg"
      email: "mhernaez@unav.es"
      affiliation: "CIMA Universidad de Navarra"
      home: "https://mikelhernaez.github.io/" 
      linkedin: "https://www.linkedin.com/in/mikel-hernaez-ab168332" 
      googleScholar: "https://scholar.google.es/citations?user=-mh8RQ8AAAAJ&hl=en" 

    - name: "Uxia Veleiro"
      logo: "/img/uxiaveleiro.jpg"
      email: "uveleirocar@unav.es"
      affiliation: "CIMA Universidad de Navarra"
      #url: "https://www.linkedin.com/in/uxiaveleiro/"
      home: "https://uxiaveleiro.github.io/"
      linkedin: "https://es.linkedin.com/in/uxiaveleiro/" 
      googleScholar: "https://scholar.google.es/citations?user=E5T8cZUAAAAJ&hl=en" # Add the Google Scholar URL here 

    - name: "Samuel Rey"
      logo: "/img/SamuelRey.jpg"
      email: "samuel.rey.escudero@urjc.es"
      affiliation: "Universidad Rey Juan Carlos"
      home: "https://gestion2.urjc.es/pdi/ver/samuel.rey.escudero"
      linkedin: "https://www.linkedin.com/in/samuel-rey-escudero-52510abb/" 
      googleScholar: "https://scholar.google.com/citations?user=fUy5BM4AAAAJ&hl=es"

