baseurl: "https://logmeetupmadrid.github.io/"
title: "LoG Madrid"
canonifyurls: true
theme: "hugo-conference"

GoogleAnalytics: ""

params:
  # Conference info
  Name: "LoG Madrid"
  Description: "LoG Meet Up Madrid"
  Date: "November 27 - 29 th"
  #Price: "Only XX€" # If your event is free, just comment this line
  Venue: "Madrid"
  Address: "Edificio XXX, Calle XXX, NN"
  City:  "Spain"
  State: "Madrid"
  Images: ["/img/badge.jpg"]
  GoogleMapsKey: "my-secret-maps-key"

  # Active sections on the website to deactivate comment out with '#'
  # you can also change order here and it will reflect on page
  Sections:
    - about
    - registration
    - cfp
    - schedule
    - speakers
    - sponsors
    #- partners
    - organizers 
    - location

  # Titles which you can translate to other languages
  Titles:
    about: "About"
    registration: "Registration"
    cfp: "Call for talks"
    location: "Location"
    schedule: "Schedule"
    speakers: "Speakers"
    sponsors: "Sponsors"
    partners: "Partners"
    organizers: "Organizers"

  # The Call To Action button at the header,
  # If you don't want this, just remove the callToAction property.
  #CallToAction:
  #  text: "Call for Talks"
  #  link: "#cfp" ## CHANGE THIS !!!

  # Fork me on GitHub, if you don't want this, just remove the forkButton property
  #ForkButton:
  #  repository: "https://github.com/jweslley/hugo-conference/"

  # List of Sponsors
  Sponsors:
    - name: "CIMA BioComp"
      logo: "/img/LogoCima.png"
      url: "https://cima.cun.es/investigacion/programas-investigacion/programa-investigacion-biologia-computacional"

    - name: "Grupo Antonio G. Marques"
      logo: "/img/logo_urjc-2.jpg"
      url: "https://www.tsc.urjc.es/~amarques/"

  # List of Partners
  Partners:
    - name: "Michi"
      logo: "/img/paw.png"
      #url: "https://gohugo.io"
    - name: "Michi"
      logo: "/img/paw.png"
      #url: "http://braziljs.org"

  # The entire schedule
  Schedule:

    - name: "Check-in & Opening"
      time: "Monday"

    # - name: "Check-in & Opening"
    #   time: "Monday - 9h00"

    # - name: "Name Surname"
    #   photo: "/img/speaker1.png"
    #   bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
    #   company: "Cat Foundation"
    #   #link:
    #   #  href: "http://twitter.com/linus"
    #   #  text: "@linus"
    #   presentation:
    #     title: "Speaker Name"
    #     time: "Monday - 9h30"

    - name: "TBA" # Name Surname
      photo: "/img/unknown1.png"
      #bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "TBA" # Cat Foundation
      #link:
      #  href: "http://twitter.com/linus"
      #  text: "@linus"
      presentation:
        title: "Plenary Talk" #Speaker Name
        time: "Monday"

    - name: "Long Talks"
      time: "Monday"

    - name: "Pitch Talks + Poster"
      time: "Monday"

    - name: "Join LoG Conference"
      time: "Monday"


    - name: "TBA" # Name and Surname
      photo: "/img/unknown1.png"
      #bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "TBA" # Cat Foundation
      #link: 
      #  href: "http://twitter.com/linus"
      #  text: "@linus"
      presentation:
        title: "Plenary Talks" # Speaker Name
        time: "Tuesday"


    - name: "Long Talks"
      time: "Tuesday"

    - name: "Pitch Talks + Poster"
      time: "Tuesday"

    - name: "Join LoG Conference"
      time: "Tuesday"


    - name: "TBA" #Name Surname
      photo: "/img/unknown1.png"
      #bio: "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo"
      company: "TBA" # Cat Foundation
      #link:
      #  href: "http://twitter.com/linus"
      #  text: "@linus"
      presentation:
        title: "Plenary Talks" # Speaker Name
        time: "Wednesday"

    - name: "Long Talks"
      time: "Wednesday"

    - name: "Pitch Talks + Poster"
      time: "Wednesday"

    - name: "Join LoG Conference"
      time: "Wednesday"


  # List of Contacts
  Contacts:

    - name: "Antonio G. Marqués"
      logo: "/img/antoniogmarques.jpg"
      email: "antonio.garcia.marques@urjc.es"
      affiliation: "Universidad Rey Juan Carlos"
      #url: "https://gohugo.io"
      home: "https://tsc.urjc.es/~amarques/" 
      linkedin: "https://es.linkedin.com/in/antonio-garc%C3%ADa-marqu%C3%A9s-1ba65254" 
      googleScholar: "https://scholar.google.com/citations?user=d05JMMkAAAAJ&hl=en" 

    - name: "Mikel Hernaez"
      logo: "/img/mikelhernaez.jpg"
      email: "mhernaez@unav.es"
      affiliation: "CIMA Universidad de Navarra"
      home: "https://mikelhernaez.github.io/" 
      linkedin: "https://www.linkedin.com/in/mikel-hernaez-ab168332" 
      googleScholar: "https://scholar.google.es/citations?user=-mh8RQ8AAAAJ&hl=en" 

    - name: "Uxia Veleiro"
      logo: "/img/uxiaveleiro.jpg"
      email: "uveleirocar@unav.es"
      affiliation: "CIMA Universidad de Navarra"
      #url: "https://www.linkedin.com/in/uxiaveleiro/"
      home: "https://uxiaveleiro.github.io/" # Add the home URL here
      linkedin: "https://es.linkedin.com/in/uxiaveleiro/" # Add the LinkedIn URL here
      googleScholar: "https://scholar.google.es/citations?user=E5T8cZUAAAAJ&hl=en" # Add the Google Scholar URL here

